sockets = ["../RBot/sockets/irc.quakenet.org"]

[plugins.autojoin]
command = [376, 422]
executable = "./autojoin.sh"

#[plugins.test]
#command = ["PRIVMSG"]
#executable = "./test.sh"
#trigger = "!test"
